export default {
  slug: 'sky-flap',
  title: 'Sky Flap',
  tagline: 'Tap to flap. Thread the neon.',
  description: 'Tap to flap a round little bird through glowing neon pillars. A free one-tap flying game you can play online in any browser, no download needed.',
  category: 'arcade',
  tags: ['one-tap', 'flying', 'reflex', 'endless', 'hyper-casual'],
  emoji: '🐤',
  colors: ['#ffd23f', '#ff4fd8'],
  bg: '#140a33',
  width: 420,
  height: 740,
  startMode: 'tap',
  readyY: 0.25,
  hint: 'Tap to flap through the gaps',
  revive: true,
  daily: true,
  lowerIsBetter: false,
  medals: [10, 30, 60],
  maxScore: 3000,
  scoreLabel: 'Gaps',
  controls: {
    touch: 'Tap anywhere to flap',
    mouse: 'Click to flap',
    keyboard: 'Space / Enter / ↑ to flap',
  },
  howTo: [
    'Tap to give the bird a quick flap upward. Gravity pulls it back down.',
    'Fly through the gap between each pair of neon pillars to score a point.',
    'Touching a pillar or the ground ends the run.',
    'The gaps get tighter and faster, and later pillars start sliding up and down.',
  ],
  tips: [
    'Use short, steady taps. Watching the bottom lip of the next gap works better than chasing the top.',
    'Flap just after you clear a pillar lip, not before: the bird rises faster than it falls.',
    'Moving gaps follow a smooth rhythm. Wait a beat, read the swing, then commit.',
  ],
  faq: [
    { q: 'Is Sky Flap free to play?', a: 'Yes. Sky Flap is completely free and runs in your web browser on phones, tablets and computers. There is nothing to install.' },
    { q: 'How do I score in Sky Flap?', a: 'You earn one point for every gap you fly through. Passing very close to a pillar counts as a near miss and chains a sparkling combo, but the score is always the number of gaps.' },
    { q: 'What is the Sky Flap Daily Challenge?', a: 'Once a day everyone flies the exact same pillar layout. Try to beat your friends on a level playing field, then come back tomorrow for a new course.' },
  ],
  about:
    'Sky Flap is a one-tap flying game set over a glowing synthwave city. You guide a round, stubborn little bird through an endless run of neon pillars, one flap at a time. Each tap gives a small burst of lift, gravity does the rest, and the whole challenge lives in the rhythm between them. The first gaps are wide and forgiving, then they tighten, the pace picks up and some pillars begin to drift. Skimming a pillar by a feather sets off a near-miss sparkle, and chaining several feels fantastic. Runs last seconds, restarts are instant, and the Daily Challenge gives everyone the same course to compete on.',
  released: '2026-09-24',
};
