export default {
  slug: 'neon-snake',
  title: 'Neon Snake',
  tagline: 'Swipe. Glow. Grow. Don’t bite yourself.',
  description: 'Steer a glowing snake around a neon grid, chain quick bites for combos and grab golden orbs before they fade. Free classic snake to play online in your browser.',
  category: 'classic',
  tags: ['snake', 'retro', 'neon', 'swipe', 'reflex', 'classic'],
  emoji: '🐍',
  colors: ['#39ff9e', '#ff3df2'],
  bg: '#07041a',
  width: 420,
  height: 740,
  startMode: 'tap',
  readyY: 0.36,
  revive: true,
  daily: true,
  lowerIsBetter: false,
  medals: [25, 60, 120],
  maxScore: 3000,
  scoreLabel: 'Points',
  controls: {
    touch: 'Swipe in any direction to turn (you can swipe ahead of time)',
    mouse: 'Drag to turn, or click beside the snake’s head to turn toward that side',
    keyboard: 'Arrow keys or WASD to steer',
  },
  howTo: [
    'Swipe or press an arrow key to steer the snake around the grid.',
    'Eat the glowing orbs to grow longer and score points.',
    'Eat the next orb quickly to build a combo for bonus points.',
    'Golden orbs are worth +5 but vanish when their ring runs out.',
    'Hitting a wall, a neon block or your own tail ends the run.',
  ],
  tips: [
    'Queue turns early: the game remembers up to two swipes, so a quick swipe-swipe makes a tight U-turn.',
    'Hug the edges while you are long and keep the middle of the grid open as your escape route.',
    'Grab golden orbs only when the path is safe. Five points are not worth a crash.',
  ],
  faq: [
    { q: 'Is Neon Snake free?', a: 'Yes. Neon Snake is free to play in any modern browser on mobile or desktop with no download, account or install.' },
    { q: 'How do combos work?', a: 'Each orb starts a short timer based on how far away it is. Reach it before the timer runs out and your combo grows, adding up to +3 bonus points per orb.' },
    { q: 'Why do blocks appear on the grid?', a: 'Every 8 orbs you reach a new level: the snake speeds up, the colours change and a few neon blocks appear. They blink for a moment before turning solid, so you always have time to react.' },
  ],
  about:
    'Neon Snake is the classic snake game rebuilt for modern screens. Your snake glides smoothly between cells instead of jumping, glows against a dark synthwave grid and gulps orbs with a satisfying pulse that ripples down its body. Swipe or tap the arrow keys to steer, and thanks to turn buffering even quick zig-zags feel precise. Chain fast bites to build combos, chase golden orbs before their countdown ring empties and survive as each level adds speed, fresh colours and new neon walls. It takes seconds to learn and far longer to master. Play endless classic mode or the Daily Challenge with the same orbs and walls for everyone.',
  released: '2026-09-24',
};
