export default {
  slug: 'rope-rumble',
  title: 'Rope Rumble',
  seoTitle: 'Rope Rumble: 2-4 Player Tug of War Game, Free Online',
  tagline: 'Heave on the beat. Drag it home.',
  description:
    'A one-button tug of war game for 1 to 4 players on one screen. Heave on the beat and drag the ring over your line. Bots fill empty seats. Free, no download.',
  category: 'party',
  party: { min: 1, max: 4 },
  tags: ['party', '2 player', '4 player', 'one-button', 'tug of war', 'local multiplayer'],
  emoji: '🪢',
  colors: ['#ff9f1c', '#7ed957'],
  bg: '#1f5a30',
  width: 420,
  height: 740,
  startMode: 'immediate',
  revive: false,
  daily: false,
  scoreLabel: 'Crowns',
  controls: {
    touch: 'Tap your corner of the screen to join, then press PLAY. In the match, tap your corner button to heave, tap as the ring around your puller turns green for a power pull, and hold to dig in. Empty seats are filled by bots.',
    mouse: 'Click a corner to join and click PLAY. Click your corner to heave, click when the ring turns green for a power pull, and hold the mouse button to dig in. Bots take every empty seat.',
    keyboard: 'Each player has one key: Z (bottom-left), M (bottom-right), P (top-right) and Q (top-left). Press your key in the lobby to join, Enter or Space to start. Tap your key to heave, hold it to dig in. Bots fill the empty seats.',
  },
  howTo: [
    'Up to 4 friends share one screen. Tap your corner (or press Z, M, P or Q) to join; bots fill the empty seats.',
    'Everyone holds a rope tied to one ring in a mud pit. Tap to heave the ring toward you.',
    'After every heave a white ring closes in on your puller. Tap as it turns green for a POWER PULL: three times stronger and cheaper on stamina.',
    'Mashing drains your stamina bar, and a heave on an empty bar just slips. Hold your button to dig in and brace while you are being dragged.',
    'Drag the ring over your own chalk line to win the round. With 3 or 4 players, anyone dragged too far the other way face-plants and is out.',
    'First to 3 crowns takes the cup. From round 2 on, a TWIST card changes the rules.',
  ],
  tips: [
    'Find the rhythm: steady taps on the green beat frantic mashing every time.',
    'A short rest refills your stamina fast. Save it for the moments that matter.',
    'Getting dragged? Hold to dig in. It soaks up most of a rival pull, but it empties your bar.',
    'Winning gives you better footing, so a small lead snowballs. Pull hard right after GO.',
    'In SUDDEN DEATH the lines creep toward the middle, and at the bell the ring goes to whoever has it closest.',
  ],
  faq: [
    { q: 'Can I play Rope Rumble alone?', a: 'Yes. Press PLAY without joining a corner and you pull the pink rope against three bots. You can also choose how many bots join from the lobby.' },
    { q: 'How do 2, 3 or 4 players share one device?', a: 'Each player owns one corner of the screen and uses only that button. On a keyboard the keys are Z, M, P and Q. It works on phones, tablets and laptops.' },
    { q: 'Is it better to mash or to tap in rhythm?', a: 'Rhythm wins. A tap in the green window is a power pull worth three normal heaves and costs less stamina. Mashing works for a burst, but it empties your bar in a couple of seconds and then your heaves slip and lose some of their pull.' },
    { q: 'What are twist cards?', a: 'From the second round on, each round draws a random rule change, such as BUTTER ROPE, GUST, GIANTS, LIGHTS OUT or SWAP, so no two rounds play the same.' },
  ],
  about:
    'Rope Rumble is a tug of war game for up to four people on one phone, tablet or laptop, where everyone plays at the same time with a single button. Each player grabs a rope tied to one brass ring in a mud pit: tap to heave it your way, hit the green beat for a power pull, and hold to dig in when a rival starts dragging you. Stamina keeps button mashers honest, the first puller to drag the ring over their own line wins the round, and in three or four player games anyone pulled too far the other way face-plants out. Play with friends or against bots with real styles, from steady rhythm pros to mashers who run out of puff, while twist cards bring greasy ropes, gusts of wind and lights out.',
  released: '2026-10-01',
};
