#!/usr/bin/env bash
# Idempotent Cloud Agent install: provisions PostgreSQL, node deps, DB schema + seed.
# Runs after the repository is checked out. Safe to run repeatedly.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PG_VERSION=16
DB_NAME=finflow
DB_USER=finflow
DB_PASSWORD=finflow

echo "==> [1/6] Ensuring PostgreSQL is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y "postgresql-${PG_VERSION}" postgresql-contrib
fi

echo "==> [2/6] Starting PostgreSQL cluster"
sudo pg_ctlcluster "$PG_VERSION" main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done
sudo -u postgres pg_isready

echo "==> [3/6] Ensuring database role and database exist"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
  END IF;
END \$\$;
ALTER ROLE ${DB_USER} CREATEDB;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
  sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
fi

echo "==> [4/6] Ensuring .env exists"
if [ ! -f .env ]; then
  cat > .env <<ENV
# Auto-generated by .cursor/install.sh for Cloud Agent development.
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}?schema=public"
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="dev-only-nextauth-secret-change-in-production"
ENV
fi

echo "==> [5/6] Installing Node dependencies"
# --legacy-peer-deps: next-auth declares an optional peer on nodemailer@^7 while the
# project pins nodemailer@^6; the dep is only used by stubbed email helpers.
npm ci --legacy-peer-deps

echo "==> [6/6] Syncing Prisma schema and seeding (only when empty)"
npx prisma db push
USER_COUNT="$(PGPASSWORD=${DB_PASSWORD} psql -h 127.0.0.1 -U "$DB_USER" -d "$DB_NAME" -tAc 'SELECT count(*) FROM "User"' 2>/dev/null || echo 0)"
if [ "${USER_COUNT:-0}" = "0" ]; then
  npm run db:seed
else
  echo "    Database already seeded (${USER_COUNT} users); skipping seed."
fi

echo "==> Install complete."
