import { chromium } from 'playwright';
const base = process.argv[2];
const browser = await chromium.launch();
const results = [];
for (const [name, viewport] of [['mobile', { width: 390, height: 844 }], ['desktop', { width: 1366, height: 900 }]]) {
  const page = await browser.newPage({ viewport, ignoreHTTPSErrors: true });
  const errors = [];
  page.on('pageerror', (e) => errors.push(String(e)));
  const res = await page.goto(base + '/', { waitUntil: 'networkidle', timeout: 90000 });
  const status = res?.status();
  const heading = await page.locator('h1').first().textContent().catch(() => null);
  const hasTabs = await page.getByText('Note photo').count();
  const hasConsent = await page.getByText("farmer's consent").count();
  const hasGallery = await page.getByRole('link', { name: 'Gallery' }).count();
  const hasGenerate = await page.getByRole('button', { name: /Generate video/ }).count();
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  await page.screenshot({ path: `smoke-${name}.png`, fullPage: false });
  results.push({ name, status, heading, hasTabs, hasConsent, hasGallery, hasGenerate, horizontalOverflow: overflow, errors });
  await page.close();
}
const page = await browser.newPage({ ignoreHTTPSErrors: true });
const g = await page.goto(base + '/gallery', { waitUntil: 'networkidle', timeout: 90000 });
results.push({ name: 'gallery', status: g?.status(), heading: await page.locator('h1').first().textContent().catch(() => null) });
const robots = await (await page.goto(base + '/robots.txt')).text();
results.push({ name: 'robots', disallowsAdmin: robots.includes('Disallow: /admin') });
const a = await page.goto(base + '/admin', { waitUntil: 'networkidle', timeout: 90000 });
results.push({ name: 'admin', status: a?.status(), heading: await page.locator('h1').first().textContent().catch(() => null) });
const u = await page.goto(base + '/admin/usage', { waitUntil: 'networkidle', timeout: 90000 });
results.push({ name: 'admin-usage', status: u?.status(), heading: await page.locator('h1').first().textContent().catch(() => null) });
await browser.close();
console.log(JSON.stringify(results, null, 2));
