export default {
  slug: 'color-rush',
  title: 'Color Rush',
  tagline: 'Only your color lets you through.',
  description: 'Tap to hop a glowing ball up through spinning color gates, passing only where the color matches yours. A free online reflex game that runs in any browser.',
  category: 'arcade',
  tags: ['one-tap', 'colors', 'reflex', 'endless', 'hyper-casual'],
  emoji: '🔵',
  colors: ['#35e0ff', '#ff3d8b'],
  bg: '#141124',
  width: 420,
  height: 740,
  startMode: 'tap',
  readyY: 0.645,
  hint: 'Pass only through your color',
  revive: true,
  daily: true,
  lowerIsBetter: false,
  medals: [10, 25, 50],
  maxScore: 3000,
  scoreLabel: 'Stars',
  controls: {
    touch: 'Tap anywhere to hop upward',
    mouse: 'Click to hop upward',
    keyboard: 'Space / Enter / ↑ to hop',
  },
  howTo: [
    'Tap to make the ball hop upward. Stop tapping and it falls.',
    'Spinning rings, bars, squares and windmills block the way, each built from four colors.',
    'You can only pass through the part that matches your ball. Any other color shatters it.',
    'Grab stars for points and touch the rainbow orbs to switch to a new color.',
    'Falling off the bottom of the screen also ends the run.',
  ],
  tips: [
    'Tap lightly to hover in place while you wait for your color to swing around.',
    'Look one obstacle ahead: after a color orb, your next gate needs a different color.',
    'For the double ring, time the outer band first, then pause inside before the inner one.',
  ],
  faq: [
    { q: 'Is Color Rush free to play?', a: 'Yes. Color Rush is a free browser game that works on phones, tablets and computers. Nothing to download and no account needed.' },
    { q: 'How do I score points in Color Rush?', a: 'Each star you collect is worth one point. Stars sit inside or just past every obstacle, so the score shows how many gates you cleared.' },
    { q: 'Does Color Rush get harder?', a: 'Yes. Obstacles spin and slide faster the higher you climb, and new shapes like double rings, windmills and twin gears join the mix.' },
  ],
  about:
    'Color Rush is a one-tap reflex game about timing and color. Your glowing ball can only pass through the part of each obstacle that matches its own color, so every gate becomes a tiny puzzle solved in real time. Tap to hop, hover, wait for the right segment to spin into place, then slip through. Rainbow orbs change your color along the way and stars reward every obstacle you clear. The climb starts with slow single rings and ramps up to sliding bars, rotating squares, windmills and twin gears that test your patience as much as your reflexes. Touch the wrong color and the ball shatters, but a new run is only a tap away.',
  released: '2026-09-24',
};
