export default {
  slug: 'blade-spin',
  title: 'Blade Spin',
  tagline: 'Throw true. Never touch steel.',
  description: 'Throw blades into a spinning wooden target without hitting the ones already stuck. Beat boss logs and slice apples in this free online browser game.',
  category: 'arcade',
  tags: ['one-tap', 'timing', 'throwing', 'reflex', 'hyper-casual'],
  emoji: '🗡️',
  colors: ['#ffb347', '#ff3d5a'],
  bg: '#1b1030',
  width: 420,
  height: 740,
  startMode: 'tap',
  readyY: 0.72,
  hint: 'Tap to throw. Miss the other blades!',
  revive: true,
  daily: true,
  lowerIsBetter: false,
  medals: [20, 50, 100],
  maxScore: 5000,
  scoreLabel: 'Blades',
  controls: {
    touch: 'Tap anywhere to throw a blade',
    mouse: 'Click to throw a blade',
    keyboard: 'Space / Enter / ↑ to throw',
  },
  howTo: [
    'A wooden target spins at the top of the screen.',
    'Tap to throw a blade straight up into it. Each blade that sticks is worth 1 point.',
    'Hitting a blade that is already stuck ends the run.',
    'Use every blade to smash the target and move to the next stage. Every fifth stage is a boss.',
    'Slice apples (+2) and gems (+3) on the rim for bonus points.',
  ],
  tips: [
    'Watch the gap, not the blades: throw the moment an open patch of wood rotates to the bottom.',
    'Boss targets speed up, stop and reverse. Wait for a change of direction to finish, then strike.',
    'Throwing fast is fine when the wood is empty. Slow down for the last two blades, when space runs out.',
  ],
  faq: [
    { q: 'Is Blade Spin free?', a: 'Yes. Blade Spin is free to play online in any modern browser on mobile or desktop, with no download or sign-up.' },
    { q: 'How does scoring work in Blade Spin?', a: 'Every blade that sticks in the target scores 1 point. Apples add 2, gems add 3, and defeating a boss target adds a 5 point bonus.' },
    { q: 'What is special about boss stages?', a: 'Every fifth stage is a steel-rimmed boss log that changes speed, pauses and reverses direction without warning. It also needs more blades to break.' },
  ],
  about:
    'Blade Spin is a one-tap throwing game about precision and patience. A wooden target spins in front of you and every tap sends a blade flying into it. Each blade that sticks becomes an obstacle for the next one, so the target slowly fills up and the safe gaps shrink. Empty your stack to shatter the log and move on to a tougher stage with faster spins, sneaky pre-stuck blades and patterns that swing back and forth. Every fifth stage brings a boss log with erratic rotation that tests your nerve. Slice apples and gems for extra points and see how many stages you can clear before you hit steel.',
  released: '2026-09-24',
};
