export default {
  slug: 'juicy-drop',
  title: 'Juicy Drop',
  tagline: 'Drop, match, merge. Grow a giant.',
  description: 'Drop cute fruit into the jar and merge matching pairs into bigger ones, all the way to a watermelon. A free physics puzzle to play online in your browser.',
  category: 'puzzle',
  tags: ['merge', 'physics', 'fruit', 'drop', 'relaxing', 'one-finger'],
  emoji: '🍉',
  colors: ['#ff5c7a', '#ffc933'],
  bg: '#ffb78c',
  width: 420,
  height: 740,
  startMode: 'immediate',
  revive: true,
  daily: true,
  lowerIsBetter: false,
  medals: [800, 2000, 4000],
  maxScore: 100000,
  scoreLabel: 'Points',
  controls: {
    touch: 'Drag to position the fruit, lift your finger to drop it',
    mouse: 'Move to position the fruit, click to drop it',
    keyboard: '← / → to move, Space / ↓ / Enter to drop',
  },
  howTo: [
    'Slide the fruit left or right along the top of the jar.',
    'Release to drop it. It rolls and settles with real physics.',
    'When two identical fruits touch they merge into the next bigger fruit.',
    'Grow cherries all the way up to a watermelon for huge points.',
    'Keep the pile below the dashed line: if fruit stays above it for two seconds, the game ends.',
  ],
  tips: [
    'Keep your biggest fruit in a bottom corner and build smaller ones outward from it, like a staircase.',
    'Check the NEXT bubble before every drop so you always know where the following fruit should go.',
    'Chain reactions score combo bonuses: set up a pair next to a fruit that matches the result.',
  ],
  faq: [
    { q: 'Is Juicy Drop free to play?', a: 'Yes. Juicy Drop is free, needs no download and plays instantly in the browser on phones, tablets and computers.' },
    { q: 'What is the order of the fruit?', a: 'Cherry, strawberry, grape, orange, persimmon, apple, pear, peach, pineapple, melon and finally watermelon. Each merge makes the next one in the chain and scores more points.' },
    { q: 'What happens when two watermelons merge?', a: 'They burst in a jackpot splash worth 100 points and free up a huge amount of space in the jar.' },
  ],
  about:
    'Juicy Drop is a cosy fruit-merge puzzle with bouncy, satisfying physics. Every fruit has a smiling face, rolls when it lands and pops into a splash of juice when it meets its twin. Drop cherries, strawberries and grapes into the jar, merge matching pairs into bigger fruit and work your way up the chain toward the mighty watermelon. The challenge is space: each merge frees room, but a careless drop can leave an awkward gap or stack fruit above the dashed line. Plan ahead with the next-fruit preview, set up chain reactions for combo bonuses and chase a new high score, or play the Daily Challenge, where everyone gets the same fruit order.',
  released: '2026-09-24',
};
