export default {
  slug: 'reflex-duel',
  title: 'Reflex Duel',
  seoTitle: 'Reflex Duel: Reaction Time Test, 1-4 Players, Free',
  tagline: 'Wait for it... DRAW! Fastest tap wins.',
  description:
    'A western reaction time test for 1 to 4 players on one screen. Wait for DRAW!, tap first and see your time in milliseconds. Bots fill seats. Free, no download.',
  category: 'party',
  party: { min: 1, max: 4 },
  tags: ['party', '2 player', '4 player', 'one-button', 'reaction time test', 'reflex', 'local multiplayer'],
  emoji: '🤠',
  colors: ['#ffb547', '#ff4f6d'],
  bg: '#2a0c25',
  width: 420,
  height: 740,
  startMode: 'immediate',
  revive: false,
  daily: false,
  scoreLabel: 'Crowns',
  controls: {
    touch: 'Tap your corner of the screen to join, then press PLAY. In the duel, keep a finger ready and tap your corner the instant DRAW! flashes. Empty seats are filled by bots.',
    mouse: 'Click a corner to join and click PLAY. When DRAW! flashes, click as fast as you can (playing solo, anywhere works). Bots take every empty seat.',
    keyboard: 'Each player has one key: Z (bottom-left), M (bottom-right), P (top-right) and Q (top-left). Press your key in the lobby to join, Enter or Space to start. Press your key the moment DRAW! flashes. Bots fill the empty seats.',
  },
  howTo: [
    'Up to 4 friends share one screen. Tap your corner (or press Z, M, P or Q) to join; bots fill the empty seats.',
    'Every player is a gunslinger by their corner. After the countdown comes a tense wait of random length.',
    'The moment DRAW! flashes, tap your corner. The fastest draw wins the round and shoots everyone else\'s hat off.',
    'Tap before the signal and you jump the gun: FALSE START, you are out for that round.',
    'Every round shows each reaction time in milliseconds, and your best time is saved. First to 5 crowns wins the cup.',
    'From round 2 on, a TWIST card changes the rules: fake signals, a silent bell, double taps, color calls and more.',
  ],
  tips: [
    'Rest your finger on your corner (or key) before the signal, so you only have to press, not move.',
    'Look at the middle of the street, not at your rivals: you react fastest to a flash right where your eyes already are.',
    'Never guess. The wait is random every round, and anything under 100 ms is a lucky guess, not a real reaction.',
    'Play with sound on: the bang of DRAW! arrives with the flash, and people react to sound a little faster than to light.',
    'Your device adds a little lag. A key press or a direct tap on the screen is usually quicker than a wireless mouse.',
  ],
  faq: [
    { q: 'What is a good reaction time?', a: 'For a simple visual signal, the average person reacts in about 200 to 250 milliseconds, and screens and input devices often add a few dozen more. Anything under 200 ms is excellent, and times under 150 ms are rare.' },
    { q: 'Can I play Reflex Duel alone?', a: 'Yes. Press PLAY without joining any corner and you are the pink gunslinger against three bots, so every round doubles as a reaction time test with rivals. Your best time is saved on your device, and you can choose fewer bots in the lobby.' },
    { q: 'How do 2, 3 or 4 players share one device?', a: 'Each player owns one corner of the screen and uses only that button. On a keyboard the keys are Z, M, P and Q. It works on phones, tablets and laptops.' },
    { q: 'How is my reaction time measured?', a: 'The clock starts on the frame where DRAW! appears and stops at the exact moment your tap or key press arrives, not at the next frame, so the result is in real milliseconds. Compare times on the same device, since every screen adds its own small delay.' },
  ],
  about:
    'Reflex Duel is a reaction time test dressed up as a sunset showdown. Up to four gunslingers stand by their corners of one phone, tablet or laptop, hands hovering over their holsters while a tumbleweed rolls past. Nobody knows how long the wait will last. The instant DRAW! flashes, the fastest tap wins the round and shoots every other hat off, and each player sees their own reaction time in milliseconds. Jump the gun and you are out. Play solo against bots with different tempers, from a sharp ace to a jumpy greenhorn, to track your best time, or settle it with friends. Twist cards add fake signals, silent bells and color calls.',
  released: '2026-10-01',
};
