"use client";

import { useState } from "react";
import { Sparkles, Copy, Check, RefreshCw } from "lucide-react";

type Insights = { summary: string; actions: string[]; emailDraft: string; engine: "ai" | "rules" };

export function AiInsightsPanel({ contactId, cachedSummary }: { contactId: string; cachedSummary: string | null }) {
  const [insights, setInsights] = useState<Insights | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  async function generate() {
    setLoading(true);
    const res = await fetch("/api/ai/insights", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ contactId }),
    });
    setLoading(false);
    if (res.ok) setInsights(await res.json());
  }

  function copyEmail() {
    if (!insights) return;
    navigator.clipboard.writeText(insights.emailDraft);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="card overflow-hidden">
      <div className="flex items-center justify-between bg-gradient-to-r from-brand-600 to-fuchsia-600 px-5 py-3.5">
        <div className="flex items-center gap-2 text-sm font-semibold text-white">
          <Sparkles className="h-4 w-4" /> AI copilot
        </div>
        <button
          onClick={generate}
          disabled={loading}
          className="inline-flex items-center gap-1.5 rounded-lg bg-white/15 px-3 py-1 text-xs font-medium text-white backdrop-blur transition hover:bg-white/25 disabled:opacity-60"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
          {loading ? "Thinking…" : insights ? "Regenerate" : "Generate insights"}
        </button>
      </div>
      <div className="p-5">
        {!insights && !cachedSummary && (
          <p className="text-sm text-slate-400">
            Get a relationship summary, next best actions and a ready-to-send follow-up email for this contact.
          </p>
        )}
        {!insights && cachedSummary && (
          <p className="text-sm leading-relaxed text-slate-600">{cachedSummary}</p>
        )}
        {insights && (
          <div className="space-y-4 text-sm">
            <p className="leading-relaxed text-slate-700">{insights.summary}</p>
            <div>
              <div className="label">Next best actions</div>
              <ul className="space-y-1.5">
                {insights.actions.map((a, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-gradient-to-r from-brand-500 to-fuchsia-500" />
                    <span className="text-slate-600">{a}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <div className="mb-1 flex items-center justify-between">
                <span className="label !mb-0">Follow-up email draft</span>
                <button onClick={copyEmail} className="inline-flex items-center gap-1 text-xs font-medium text-brand-600 hover:underline">
                  {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
                  {copied ? "Copied" : "Copy"}
                </button>
              </div>
              <pre className="whitespace-pre-wrap rounded-xl bg-slate-50 p-3 font-sans text-xs leading-relaxed text-slate-600">
                {insights.emailDraft}
              </pre>
            </div>
            <div className="text-[11px] text-slate-400">
              {insights.engine === "ai"
                ? "Generated by the configured AI model."
                : "Generated by the built-in rules engine — set AI_API_KEY to upgrade to LLM-powered insights."}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
