export default {
  slug: 'brick-barrage',
  title: 'Brick Barrage',
  tagline: 'Aim. Unleash the volley. Break it all.',
  description: 'Aim, fire a volley of bouncing balls and smash numbered bricks before the wall reaches you. A free, satisfying ball shooter you play online in your browser.',
  category: 'arcade',
  tags: ['ball-shooter', 'bricks', 'aiming', 'turn-based', 'one-finger', 'hyper-casual'],
  emoji: '🟪',
  colors: ['#22d3ee', '#f43f5e'],
  bg: '#120e2a',
  width: 420,
  height: 740,
  startMode: 'immediate',
  revive: true,
  daily: true,
  lowerIsBetter: false,
  medals: [25, 50, 90],
  maxScore: 5000,
  scoreLabel: 'Turn',
  controls: {
    touch: 'Drag to aim, release to fire. Tap during a volley to speed it up.',
    mouse: 'Point to aim, click to fire. Click during a volley to speed it up.',
    keyboard: '← / → to aim, Space / Enter / ↑ to fire (and to speed up)',
  },
  howTo: [
    'Drag from anywhere to aim: the dotted line shows your path and the first rebound.',
    'Release to fire your whole volley. Every ball bounces off walls and bricks.',
    'Each hit knocks one point off a brick. Bring it to zero and it shatters.',
    'Collect the glowing rings to add an extra ball to your volley.',
    'After every turn the wall steps down a row. If a brick reaches the red line, it is over.',
  ],
  tips: [
    'Bank shots off the side walls to sneak balls behind the wall: they rattle around the top lane and deal massive damage.',
    'Grab +1 rings early. More balls now means far easier turns later.',
    'Clear the lowest bricks first when they get close to the red line, even if it means a smaller combo.',
  ],
  faq: [
    { q: 'Is Brick Barrage free to play?', a: 'Yes. Brick Barrage is completely free and runs instantly in any modern browser on phone, tablet or desktop, with no download or sign-up.' },
    { q: 'How do I get more balls?', a: 'Every new row contains a glowing +1 ring. Hit it with any ball during a volley and your volley grows by one ball from the next turn on.' },
    { q: 'What is the Daily Challenge?', a: 'Once per day every player gets the exact same sequence of brick rows and rings. Play it, then compare how many turns you survived with your friends.' },
  ],
  about:
    'Brick Barrage is a turn-based ball shooter built for quick sessions and long streaks. Line up a shot, release a volley and watch dozens of balls ricochet through a wall of numbered bricks, each impact chiming a little higher than the last. Bricks shatter into confetti-like shards, rings add balls to your arsenal and a well-placed bank shot can trap your volley behind the wall for a spectacular chain of hits. Every turn the wall creeps one row closer and the numbers climb, so planning your angles matters as much as quick reflexes. Play the endless classic mode or the Daily Challenge, where everyone gets the same bricks.',
  released: '2026-09-24',
};
