export default {
  slug: 'puck-panic',
  title: 'Puck Panic',
  seoTitle: 'Puck Panic: 2-4 Player Air Hockey Game, Free Online',
  tagline: 'Hold to smash. Let go to save.',
  description:
    'Neon air hockey for 1 to 4 players on one screen. Hold one button to charge the puck, let go to guard your goal. Bots fill empty seats. Free, no download.',
  category: 'party',
  party: { min: 1, max: 4 },
  tags: ['party', '2 player', '4 player', 'one-button', 'air hockey', 'local multiplayer'],
  emoji: '🥅',
  colors: ['#35f0d0', '#ff7847'],
  bg: '#03161a',
  width: 420,
  height: 740,
  startMode: 'immediate',
  revive: false,
  daily: false,
  scoreLabel: 'Crowns',
  controls: {
    touch: 'Tap your corner of the screen to join, then press PLAY. In the match, hold your corner button to send your mallet after the puck and let go to glide back to your goal. Empty seats are filled by bots.',
    mouse: 'Click a corner to join and click PLAY. Hold the mouse button on your corner to charge the puck, release to return to your goal. Bots take every empty seat.',
    keyboard: 'Each player has one key: Z (bottom-left), M (bottom-right), P (top-right) and Q (top-left). Press your key in the lobby to join, Enter or Space to start. Hold your key to charge the puck, let go to guard your goal. Bots fill the empty seats.',
  },
  howTo: [
    'Up to 4 friends share one screen. Tap your corner (or press Z, M, P or Q) to join; bots fill the empty seats.',
    'Everyone owns one goal and one mallet. Two players get classic air hockey, bottom goal against top goal; three or four players add goals on the sides.',
    'Hold your button and your mallet charges at the puck. The faster it is moving when it connects, the harder the shot.',
    'Let go and your mallet glides back to guard the middle of your goal. Charge for too long and your goal is wide open.',
    'A puck in your goal costs one of your 3 lives. Lose them all and your goal closes for good. The last mallet standing wins the crown.',
    'A second puck drops in after 20 seconds, then RUSH adds a third and keeps every puck flying. If the 60 seconds run out, the most lives left wins. First to 3 crowns takes the cup.',
  ],
  tips: [
    'Tap for a quick jab: your mallet kicks toward the puck and comes straight back, so your goal is never open for long.',
    'Charge from in front of your goal so you hit the puck away from it. Chasing a puck from behind pushes it toward your own net.',
    'The puck glides on the air table and bounces off every rail. Bank shots off the side rails sneak past a guarding mallet.',
    'Your mallet reaches only a little past the middle of the table, and it can never enter another player\'s crease.',
    'When a rival is down to one life, their goal flashes white. Keep the pucks flowing their way and stay home yourself.',
  ],
  faq: [
    { q: 'Can I play Puck Panic alone?', a: 'Yes. Press PLAY without joining a corner and you play the pink mallet against three bots. Tap the bots button in the lobby to face a single bot on a classic two-goal table instead.' },
    { q: 'How do 2, 3 or 4 players share one device?', a: 'Each player owns one corner of the screen and uses only that button. On a keyboard the keys are Z, M, P and Q. The table adapts to the group: two players defend the top and bottom goals, three or four players add goals on the sides.' },
    { q: 'How is Puck Panic different from normal air hockey?', a: 'In regular air hockey you steer the mallet by hand. Here you have one button: hold it and your mallet chases the puck on its own, let go and it returns to guard your goal. The skill is in timing your charges, and up to four people can share one table.' },
    { q: 'What are twist cards?', a: 'From the second round on, each round draws a random rule change, such as MULTI PUCK, ICE TABLE, WIDE GOALS, GIANTS, LIGHTS OUT or SWAP, so no two rounds play the same.' },
  ],
  about:
    'Puck Panic is a fast air hockey game for up to four people on one phone, tablet or laptop, where everyone plays at the same time with a single button. Hold it and your mallet charges across the glowing table after the puck; let go and it glides back to guard your goal. That one choice between attacking and defending makes every rally tense, because a big smash always leaves your own net open. Two players get a classic top and bottom table, while three or four add goals on the sides for proper chaos. Everyone has three lives, a second puck joins after twenty seconds, and twist cards like Multi Puck, Ice Table and Wide Goals keep every round different. Play with friends or against bots with their own styles.',
  released: '2026-10-01',
};
